#This file is auto-generated by buildInit. Manual changes will be lost
from setScale import setScale
from saveFileWaveform import saveFileWaveform
from getAcqType import getAcqType
from getcurrentDC import getcurrentDC
from setcurrentDC import setcurrentDC
from setdisplayscreen import setdisplayscreen
from setImpedanceChannel import setImpedanceChannel
from getTrigMode import getTrigMode
from getIDN import getIDN
from setAcqType import setAcqType
from setvoltageDC import setvoltageDC
from getcommand import getcommand
from getImpedanceChannel import getImpedanceChannel
from setcommand import setcommand
from setTrigMode import setTrigMode
from getcurrentAC import getcurrentAC
from getvoltageDC import getvoltageDC
from getvoltageAC import getvoltageAC
command = {
  'setScale': setScale,
  'saveFileWaveform': saveFileWaveform,
  'getAcqType': getAcqType,
  'getcurrentDC': getcurrentDC,
  'setcurrentDC': setcurrentDC,
  'setdisplayscreen': setdisplayscreen,
  'setImpedanceChannel': setImpedanceChannel,
  'getTrigMode': getTrigMode,
  'getIDN': getIDN,
  'setAcqType': setAcqType,
  'setvoltageDC': setvoltageDC,
  'getcommand': getcommand,
  'getImpedanceChannel': getImpedanceChannel,
  'setcommand': setcommand,
  'setTrigMode': setTrigMode,
  'getcurrentAC': getcurrentAC,
  'getvoltageDC': getvoltageDC,
  'getvoltageAC': getvoltageAC,
}