# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeviceControlInterface.ui'
#
# Created: Wed Mar 21 19:09:35 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(829, 588)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "GPIB Gateway IP Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditIP = QtGui.QLineEdit(self.centralwidget)
        self.lineEditIP.setText(_fromUtf8(""))
        self.lineEditIP.setObjectName(_fromUtf8("lineEditIP"))
        self.horizontalLayout_3.addWidget(self.lineEditIP)
        self.pushButtonFindDevices = QtGui.QPushButton(self.centralwidget)
        self.pushButtonFindDevices.setText(QtGui.QApplication.translate("MainWindow", "Find Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFindDevices.setObjectName(_fromUtf8("pushButtonFindDevices"))
        self.horizontalLayout_3.addWidget(self.pushButtonFindDevices)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.listWidgetDevices = QtGui.QListWidget(self.splitter)
        self.listWidgetDevices.setObjectName(_fromUtf8("listWidgetDevices"))
        self.listWidgetCommands = QtGui.QListWidget(self.splitter)
        self.listWidgetCommands.setObjectName(_fromUtf8("listWidgetCommands"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelArg1 = QtGui.QLabel(self.widget)
        self.labelArg1.setText(QtGui.QApplication.translate("MainWindow", "arg1:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelArg1.setObjectName(_fromUtf8("labelArg1"))
        self.horizontalLayout.addWidget(self.labelArg1)
        self.lineEditArg1 = QtGui.QLineEdit(self.widget)
        self.lineEditArg1.setObjectName(_fromUtf8("lineEditArg1"))
        self.horizontalLayout.addWidget(self.lineEditArg1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelArg2 = QtGui.QLabel(self.widget)
        self.labelArg2.setText(QtGui.QApplication.translate("MainWindow", "arg2:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelArg2.setObjectName(_fromUtf8("labelArg2"))
        self.horizontalLayout_4.addWidget(self.labelArg2)
        self.lineEditArg2 = QtGui.QLineEdit(self.widget)
        self.lineEditArg2.setObjectName(_fromUtf8("lineEditArg2"))
        self.horizontalLayout_4.addWidget(self.lineEditArg2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelArg3 = QtGui.QLabel(self.widget)
        self.labelArg3.setText(QtGui.QApplication.translate("MainWindow", "arg3:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelArg3.setObjectName(_fromUtf8("labelArg3"))
        self.horizontalLayout_5.addWidget(self.labelArg3)
        self.lineEditArg3 = QtGui.QLineEdit(self.widget)
        self.lineEditArg3.setObjectName(_fromUtf8("lineEditArg3"))
        self.horizontalLayout_5.addWidget(self.lineEditArg3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelArg4 = QtGui.QLabel(self.widget)
        self.labelArg4.setText(QtGui.QApplication.translate("MainWindow", "arg4:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelArg4.setObjectName(_fromUtf8("labelArg4"))
        self.horizontalLayout_6.addWidget(self.labelArg4)
        self.lineEditArg4 = QtGui.QLineEdit(self.widget)
        self.lineEditArg4.setObjectName(_fromUtf8("lineEditArg4"))
        self.horizontalLayout_6.addWidget(self.lineEditArg4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelArg5 = QtGui.QLabel(self.widget)
        self.labelArg5.setText(QtGui.QApplication.translate("MainWindow", "arg5:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelArg5.setObjectName(_fromUtf8("labelArg5"))
        self.horizontalLayout_7.addWidget(self.labelArg5)
        self.lineEditArg5 = QtGui.QLineEdit(self.widget)
        self.lineEditArg5.setObjectName(_fromUtf8("lineEditArg5"))
        self.horizontalLayout_7.addWidget(self.lineEditArg5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButtonGet = QtGui.QPushButton(self.centralwidget)
        self.pushButtonGet.setText(QtGui.QApplication.translate("MainWindow", "Get Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGet.setObjectName(_fromUtf8("pushButtonGet"))
        self.horizontalLayout_2.addWidget(self.pushButtonGet)
        self.lineEditResult = QtGui.QLineEdit(self.centralwidget)
        self.lineEditResult.setObjectName(_fromUtf8("lineEditResult"))
        self.horizontalLayout_2.addWidget(self.lineEditResult)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

