# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addingmodule.ui'
#
# Created: Sun Apr  8 15:39:53 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(803, 509)
        Wizard.setWindowTitle(QtGui.QApplication.translate("Wizard", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.layoutWidget = QtGui.QWidget(self.wizardPage1)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 110, 351, 258))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setText(QtGui.QApplication.translate("Wizard", "This wizard will help you to generate a module\n"
" (plugin) for DeathRay software. Please, follow\n"
" the step carefully.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setText(QtGui.QApplication.translate("Wizard", "Before we start, you have to know the SCPI\n"
" command for this module.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setText(QtGui.QApplication.translate("Wizard", "Notes:\n"
"1) the wizard can not build a complex module\n"
" (for example, use more than one SCPI command\n"
" to be achive the goal for one device).\n"
"2) After the module generated, It is going to\n"
" in the gpib_command folder inside DeathRay folder.\n"
"3) Please, review the generated module. Maybe, \n"
"there are some errors. ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setText(QtGui.QApplication.translate("Wizard", "When you are ready, Please, click Next.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label_23 = QtGui.QLabel(self.wizardPage1)
        self.label_23.setGeometry(QtCore.QRect(90, 380, 391, 31))
        self.label_23.setText(QtGui.QApplication.translate("Wizard", "Note: *  boxes are required.Or, The module will not work. ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.label_5 = QtGui.QLabel(self.wizardPage2)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 701, 31))
        self.label_5.setText(QtGui.QApplication.translate("Wizard", "General Inofrmation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line = QtGui.QFrame(self.wizardPage2)
        self.line.setGeometry(QtCore.QRect(-10, 30, 761, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.wizardPage2)
        self.line_2.setGeometry(QtCore.QRect(-10, 220, 781, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_14 = QtGui.QLabel(self.wizardPage2)
        self.label_14.setGeometry(QtCore.QRect(20, 230, 161, 31))
        self.label_14.setText(QtGui.QApplication.translate("Wizard", "Module Inofrmation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.line_3 = QtGui.QFrame(self.wizardPage2)
        self.line_3.setGeometry(QtCore.QRect(-10, 252, 781, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.wizardPage2)
        self.line_4.setGeometry(QtCore.QRect(-10, 1, 761, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.layoutWidget1 = QtGui.QWidget(self.wizardPage2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 110, 411, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setText(QtGui.QApplication.translate("Wizard", "* Your name:                   ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setText(QtGui.QApplication.translate("Wizard", "Ex: Bob Michael", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.line_5 = QtGui.QFrame(self.wizardPage2)
        self.line_5.setGeometry(QtCore.QRect(0, 170, 761, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.layoutWidget2 = QtGui.QWidget(self.wizardPage2)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 270, 755, 171))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_19 = QtGui.QLabel(self.layoutWidget2)
        self.label_19.setText(QtGui.QApplication.translate("Wizard", "* First device name  : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_9.addWidget(self.label_19)
        self.lineEdit_5 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_9.addWidget(self.lineEdit_5)
        self.label_17 = QtGui.QLabel(self.layoutWidget2)
        self.label_17.setText(QtGui.QApplication.translate("Wizard", "Ex: 34401a (without the company pre-fix), Run getIDN to get the name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        self.label_20.setText(QtGui.QApplication.translate("Wizard", "Second device name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_10.addWidget(self.label_20)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_10.addWidget(self.lineEdit_7)
        self.label_18 = QtGui.QLabel(self.layoutWidget2)
        self.label_18.setText(QtGui.QApplication.translate("Wizard", "Ex: 34401a (without the company pre-fix), Run getIDN to get the name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_10.addWidget(self.label_18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_15 = QtGui.QLabel(self.layoutWidget2)
        self.label_15.setText(QtGui.QApplication.translate("Wizard", "Third device name:    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_11.addWidget(self.label_15)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.horizontalLayout_11.addWidget(self.lineEdit_8)
        self.label_21 = QtGui.QLabel(self.layoutWidget2)
        self.label_21.setText(QtGui.QApplication.translate("Wizard", "Ex: 34401a (without the company pre-fix), Run getIDN to get the name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_11.addWidget(self.label_21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_16 = QtGui.QLabel(self.layoutWidget2)
        self.label_16.setText(QtGui.QApplication.translate("Wizard", "Fourth device name: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_12.addWidget(self.label_16)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_12.addWidget(self.lineEdit_6)
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setText(QtGui.QApplication.translate("Wizard", "Ex: 34401a (without the company pre-fix), Run getIDN to get the name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_12.addWidget(self.label_22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_25 = QtGui.QLabel(self.layoutWidget2)
        self.label_25.setText(QtGui.QApplication.translate("Wizard", "Fifth device name:     ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_13.addWidget(self.label_25)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.horizontalLayout_13.addWidget(self.lineEdit_9)
        self.label_26 = QtGui.QLabel(self.layoutWidget2)
        self.label_26.setText(QtGui.QApplication.translate("Wizard", "Ex: 34401a (without the company pre-fix), Run getIDN to get the name.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_13.addWidget(self.label_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.layoutWidget3 = QtGui.QWidget(self.wizardPage2)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 80, 583, 31))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setText(QtGui.QApplication.translate("Wizard", "* Module name:             ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_3.addWidget(self.label_8)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        self.label_9.setText(QtGui.QApplication.translate("Wizard", "Ex: DC voltage Reader (from getvoltageDC)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_4.addWidget(self.label_9)
        self.layoutWidget4 = QtGui.QWidget(self.wizardPage2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 50, 529, 31))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.layoutWidget4)
        self.label_6.setText(QtGui.QApplication.translate("Wizard", "* Name of module file:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        self.label_7.setText(QtGui.QApplication.translate("Wizard", "Ex: voltageDC (from getvoltageDC)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.layoutWidget5 = QtGui.QWidget(self.wizardPage2)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 140, 701, 31))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_12 = QtGui.QLabel(self.layoutWidget5)
        self.label_12.setText(QtGui.QApplication.translate("Wizard", "* Module\'s goal:             ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_7.addWidget(self.label_12)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget5)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.label_13 = QtGui.QLabel(self.layoutWidget5)
        self.label_13.setText(QtGui.QApplication.translate("Wizard", "Ex:This moduel returns the DC voltage (from getvoltageDC)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.layoutWidget6 = QtGui.QWidget(self.wizardPage2)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 193, 521, 24))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_27 = QtGui.QLabel(self.layoutWidget6)
        self.label_27.setText(QtGui.QApplication.translate("Wizard", "Is it \"get\" kind? (if not, it will be \"set\" automatic): ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_14.addWidget(self.label_27)
        self.checkBox_21 = QtGui.QCheckBox(self.layoutWidget6)
        self.checkBox_21.setText(QtGui.QApplication.translate("Wizard", "YES", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.horizontalLayout_14.addWidget(self.checkBox_21)
        Wizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.line_6 = QtGui.QFrame(self.wizardPage3)
        self.line_6.setGeometry(QtCore.QRect(0, 30, 761, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.wizardPage3)
        self.line_7.setGeometry(QtCore.QRect(0, 1, 761, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_24 = QtGui.QLabel(self.wizardPage3)
        self.label_24.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.label_24.setText(QtGui.QApplication.translate("Wizard", "SCPI Inofrmation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_37 = QtGui.QLabel(self.wizardPage3)
        self.label_37.setGeometry(QtCore.QRect(20, 90, 581, 17))
        self.label_37.setText(QtGui.QApplication.translate("Wizard", "Note: Enter the first part of the SCPI (until you reach the first space) in the first box:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.wizardPage3)
        self.label_38.setGeometry(QtCore.QRect(20, 110, 381, 17))
        self.label_38.setText(QtGui.QApplication.translate("Wizard", "Ex: meas:volt:dc?  ===> meas:volt:dc?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.wizardPage3)
        self.label_39.setGeometry(QtCore.QRect(20, 130, 381, 17))
        self.label_39.setText(QtGui.QApplication.translate("Wizard", "Ex: disp:text <text>  ===> disp:text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.wizardPage3)
        self.label_40.setGeometry(QtCore.QRect(20, 50, 691, 31))
        self.label_40.setText(QtGui.QApplication.translate("Wizard", "Note: This tool does not support multable SCPI commands (see set voltage DC for e3631section under\n"
" \"do\" function). ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.wizardPage3)
        self.label_41.setGeometry(QtCore.QRect(20, 150, 681, 61))
        self.label_41.setText(QtGui.QApplication.translate("Wizard", "Note: If SCPI command needs an input (the tool only support one input), enter the input in the second \n"
"part of the SCPI (after first space) in the second box without \"<>\". Make sure its human readable (do not \n"
"write have of the word):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.wizardPage3)
        self.label_42.setGeometry(QtCore.QRect(20, 210, 381, 17))
        self.label_42.setText(QtGui.QApplication.translate("Wizard", "Ex: disp:text <text>  ===> text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_29 = QtGui.QLabel(self.wizardPage3)
        self.label_29.setGeometry(QtCore.QRect(90, 240, 91, 16))
        self.label_29.setText(QtGui.QApplication.translate("Wizard", "Device\'s SCPI: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_33 = QtGui.QLabel(self.wizardPage3)
        self.label_33.setGeometry(QtCore.QRect(200, 230, 111, 31))
        self.label_33.setText(QtGui.QApplication.translate("Wizard", "Required Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.wizardPage3)
        self.label_34.setGeometry(QtCore.QRect(320, 230, 61, 31))
        self.label_34.setText(QtGui.QApplication.translate("Wizard", " Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_36 = QtGui.QLabel(self.wizardPage3)
        self.label_36.setGeometry(QtCore.QRect(430, 230, 61, 31))
        self.label_36.setText(QtGui.QApplication.translate("Wizard", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_43 = QtGui.QLabel(self.wizardPage3)
        self.label_43.setGeometry(QtCore.QRect(590, 230, 91, 31))
        self.label_43.setText(QtGui.QApplication.translate("Wizard", " Dafult value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.widget = QtGui.QWidget(self.wizardPage3)
        self.widget.setGeometry(QtCore.QRect(20, 270, 711, 161))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_35 = QtGui.QLabel(self.widget)
        self.label_35.setText(QtGui.QApplication.translate("Wizard", "* First:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_6.addWidget(self.label_35)
        self.label_32 = QtGui.QLabel(self.widget)
        self.label_32.setText(QtGui.QApplication.translate("Wizard", "Second:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_6.addWidget(self.label_32)
        self.label_30 = QtGui.QLabel(self.widget)
        self.label_30.setText(QtGui.QApplication.translate("Wizard", "Third:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_6.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.widget)
        self.label_31.setText(QtGui.QApplication.translate("Wizard", "Fourth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_6.addWidget(self.label_31)
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setText(QtGui.QApplication.translate("Wizard", "Fifth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit_11 = QtGui.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.verticalLayout_4.addWidget(self.lineEdit_11)
        self.lineEdit_14 = QtGui.QLineEdit(self.widget)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.verticalLayout_4.addWidget(self.lineEdit_14)
        self.lineEdit_13 = QtGui.QLineEdit(self.widget)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.verticalLayout_4.addWidget(self.lineEdit_13)
        self.lineEdit_12 = QtGui.QLineEdit(self.widget)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.verticalLayout_4.addWidget(self.lineEdit_12)
        self.lineEdit_10 = QtGui.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.verticalLayout_4.addWidget(self.lineEdit_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox = QtGui.QCheckBox(self.widget)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtGui.QCheckBox(self.widget)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtGui.QCheckBox(self.widget)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtGui.QCheckBox(self.widget)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_5 = QtGui.QCheckBox(self.widget)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lineEdit_15 = QtGui.QLineEdit(self.widget)
        self.lineEdit_15.setEnabled(False)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.verticalLayout_5.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtGui.QLineEdit(self.widget)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.verticalLayout_5.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtGui.QLineEdit(self.widget)
        self.lineEdit_17.setEnabled(False)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.verticalLayout_5.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtGui.QLineEdit(self.widget)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.verticalLayout_5.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtGui.QLineEdit(self.widget)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.verticalLayout_5.addWidget(self.lineEdit_19)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_6 = QtGui.QCheckBox(self.widget)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setText(QtGui.QApplication.translate("Wizard", "Int", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout.addWidget(self.checkBox_6, 0, 0, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.widget)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setText(QtGui.QApplication.translate("Wizard", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.widget)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setText(QtGui.QApplication.translate("Wizard", "Str", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout.addWidget(self.checkBox_8, 0, 2, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.widget)
        self.checkBox_10.setEnabled(False)
        self.checkBox_10.setText(QtGui.QApplication.translate("Wizard", "Int", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 1, 0, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.widget)
        self.checkBox_11.setEnabled(False)
        self.checkBox_11.setText(QtGui.QApplication.translate("Wizard", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 1, 1, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.widget)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setText(QtGui.QApplication.translate("Wizard", "Str", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout.addWidget(self.checkBox_9, 1, 2, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.widget)
        self.checkBox_13.setEnabled(False)
        self.checkBox_13.setText(QtGui.QApplication.translate("Wizard", "Int", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout.addWidget(self.checkBox_13, 2, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.widget)
        self.checkBox_14.setEnabled(False)
        self.checkBox_14.setText(QtGui.QApplication.translate("Wizard", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout.addWidget(self.checkBox_14, 2, 1, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.widget)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setText(QtGui.QApplication.translate("Wizard", "Str", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 2, 2, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.widget)
        self.checkBox_16.setEnabled(False)
        self.checkBox_16.setText(QtGui.QApplication.translate("Wizard", "Int", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout.addWidget(self.checkBox_16, 3, 0, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.widget)
        self.checkBox_17.setEnabled(False)
        self.checkBox_17.setText(QtGui.QApplication.translate("Wizard", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout.addWidget(self.checkBox_17, 3, 1, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.widget)
        self.checkBox_15.setEnabled(False)
        self.checkBox_15.setText(QtGui.QApplication.translate("Wizard", "Str", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridLayout.addWidget(self.checkBox_15, 3, 2, 1, 1)
        self.checkBox_19 = QtGui.QCheckBox(self.widget)
        self.checkBox_19.setEnabled(False)
        self.checkBox_19.setText(QtGui.QApplication.translate("Wizard", "Int", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridLayout.addWidget(self.checkBox_19, 4, 0, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.widget)
        self.checkBox_20.setEnabled(False)
        self.checkBox_20.setText(QtGui.QApplication.translate("Wizard", "float", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout.addWidget(self.checkBox_20, 4, 1, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.widget)
        self.checkBox_18.setEnabled(False)
        self.checkBox_18.setText(QtGui.QApplication.translate("Wizard", "Str", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout.addWidget(self.checkBox_18, 4, 2, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lineEdit_20 = QtGui.QLineEdit(self.widget)
        self.lineEdit_20.setEnabled(False)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.verticalLayout_7.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtGui.QLineEdit(self.widget)
        self.lineEdit_21.setEnabled(False)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.verticalLayout_7.addWidget(self.lineEdit_21)
        self.lineEdit_22 = QtGui.QLineEdit(self.widget)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.verticalLayout_7.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtGui.QLineEdit(self.widget)
        self.lineEdit_23.setEnabled(False)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.verticalLayout_7.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtGui.QLineEdit(self.widget)
        self.lineEdit_24.setEnabled(False)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.verticalLayout_7.addWidget(self.lineEdit_24)
        self.horizontalLayout_16.addLayout(self.verticalLayout_7)
        Wizard.addPage(self.wizardPage3)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        Wizard.addPage(self.wizardPage)
        self.wizardPage10 = QtGui.QWizardPage()
        self.wizardPage10.setObjectName(_fromUtf8("wizardPage10"))
        Wizard.addPage(self.wizardPage10)

        self.retranslateUi(Wizard)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_15.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_16.setEnabled)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_17.setEnabled)
        QtCore.QObject.connect(self.checkBox_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_18.setEnabled)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_19.setEnabled)
        QtCore.QObject.connect(self.checkBox_6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_8.setDisabled)
        QtCore.QObject.connect(self.checkBox_7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_8.setDisabled)
        QtCore.QObject.connect(self.checkBox_7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_6.setChecked)
        QtCore.QObject.connect(self.checkBox_8, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_7.setDisabled)
        QtCore.QObject.connect(self.checkBox_8, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_7.setDisabled)
        QtCore.QObject.connect(self.checkBox_8, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_6.setDisabled)
        QtCore.QObject.connect(self.checkBox_10, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_9.setDisabled)
        QtCore.QObject.connect(self.checkBox_11, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_9.setDisabled)
        QtCore.QObject.connect(self.checkBox_9, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_11.setDisabled)
        QtCore.QObject.connect(self.checkBox_9, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_10.setDisabled)
        QtCore.QObject.connect(self.checkBox_11, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_10.setChecked)
        QtCore.QObject.connect(self.checkBox_13, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_12.setDisabled)
        QtCore.QObject.connect(self.checkBox_14, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_13.setChecked)
        QtCore.QObject.connect(self.checkBox_12, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_14.setDisabled)
        QtCore.QObject.connect(self.checkBox_12, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_13.setDisabled)
        QtCore.QObject.connect(self.checkBox_17, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_16.setChecked)
        QtCore.QObject.connect(self.checkBox_16, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_15.setDisabled)
        QtCore.QObject.connect(self.checkBox_15, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_17.setDisabled)
        QtCore.QObject.connect(self.checkBox_15, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_16.setDisabled)
        QtCore.QObject.connect(self.checkBox_20, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_19.setChecked)
        QtCore.QObject.connect(self.checkBox_19, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_18.setDisabled)
        QtCore.QObject.connect(self.checkBox_18, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_20.setDisabled)
        QtCore.QObject.connect(self.checkBox_18, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_19.setDisabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_6.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_7.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_8.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_10.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_11.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_9.setEnabled)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_13.setEnabled)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_14.setEnabled)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_12.setEnabled)
        QtCore.QObject.connect(self.checkBox_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_16.setEnabled)
        QtCore.QObject.connect(self.checkBox_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_17.setEnabled)
        QtCore.QObject.connect(self.checkBox_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_15.setEnabled)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_19.setEnabled)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_20.setEnabled)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_18.setEnabled)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_20.setEnabled)
        QtCore.QObject.connect(self.checkBox_2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_21.setEnabled)
        QtCore.QObject.connect(self.checkBox_3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_22.setEnabled)
        QtCore.QObject.connect(self.checkBox_4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_23.setEnabled)
        QtCore.QObject.connect(self.checkBox_5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_24.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        pass

