#This file is auto-generated by reloadFPGA. Manual changes will be lost
import pulse_width_count
import register_error
experiment = {
  'pulse_width_count': (pulse_width_count,[1]),
  'register_error': (register_error,[1]),
}