#! /usr/bin/env python

# Name: reloadFPGA.py
# Made by: Jack Minardi
# Date: 4/1/12
# Goal: Make sure the fpga_scripts __init__.py file is up to date.
# Result: new __init__.py file


import glob, os

initFile = open('./fpga_scripts/__init__.py', 'w')
scriptList = []

#find all the scripts and append them to scriptList
for pyFile in glob.glob('./fpga_scripts/*.py'):
  script = os.path.split(pyFile)[1].split('.')[0]
  if '__init__' not in script:
    f = open(pyFile)
    for line in f:
      if 'self.plotsUsed' in line:
        plotsUsed = eval(line[line.find('['):line.find(']')+1])
        scriptList.append((script, plotsUsed))

#Add in the warning about this script being auto-generated
initFile.write('#This file is auto-generated by reloadFPGA. Manual changes will be lost\n')

#add the 'from command import command' lines
for script, plotsUsed in scriptList:
  initFile.write('import '+script+'\n')

#build the command dictionary
initFile.write('experiment = {\n')
for script, plotsUsed in scriptList:
  initFile.write("  '"+script+"': ("+script+","+str(plotsUsed)+"),\n")
initFile.write('}')

initFile.close()
